import type {buildDiverterLab,DiverterHandles,DiverterOptions} from './diverter-scene';
import type {createSurveyArchive} from './survey-ledger';
export const GATE_YARD_PALLET:NonNullable<DiverterOptions['floor']>;
export const GATE_YARD_LEVER:NonNullable<DiverterOptions['switch']>;
export const GATE_YARD_ARMS:readonly ['m4','t9'];
export const GATE_YARD_PROGRESS_KEY:'rail-golf-gate-yard-v1';
export const GATE_YARD_LIBRARY_SUFFIX:'-gate-yard-v1';
export const GATE_YARD_SURVEY_DB:'rail-golf-gate-yard-survey';
export const GATE_YARD_PALLET_KEY:'rail-golf:gate-yard:m4:pallet';
export const GATE_YARD_RELATIONS:readonly ['fresh','adjust','retry','recall'];
export type GateYardArm='m4'|'t9';
export type GateYardRelation=(typeof GATE_YARD_RELATIONS)[number];
export function parseGateYardArm(value:string|null|undefined):GateYardArm|null;
export function gateYardCarries(arm:GateYardArm):boolean;
export function gateYardPrefix(arm:GateYardArm):string;
export function gateYardStorage(storage:Pick<Storage,'length'|'key'|'getItem'|'setItem'|'removeItem'>,arm:GateYardArm):Storage;
export function readCarryPallet(sessionStorage:Pick<Storage,'getItem'>):'A'|'B';
export function writeCarryPallet(sessionStorage:Pick<Storage,'setItem'>,state:'A'|'B'):void;
export function gateYardAddressState(arm:GateYardArm,current:'A'|'B',action:'adjust'|'retry'|'recall'|'reset'):'A'|'B';
export function gateYardLoadState(arm:GateYardArm,sessionStorage:Pick<Storage,'getItem'>):'A'|'B';
export function gateYardContactCaption(kind:string):'PALLET'|'LEVER'|null;
export function gateYardLiveCaptions(ledger:readonly {kind?:string;feature?:string;label?:string;surface?:string}[]):{label:string;sourceIndex:number}[];
export function gateYardShotFacts(contacts:readonly {kind?:string}[]|undefined,ledger:readonly {kind?:string;surface?:string}[]|undefined):{leverContact:boolean;palletContact:boolean};
export function annotateGateYardTicket<T extends object>(ticket:T,arm:GateYardArm,relation:GateYardRelation,endFloor:'A'|'B',contacts:readonly {kind?:string}[]|undefined,ledger:readonly {kind?:string;surface?:string}[]|undefined):T&{arm:GateYardArm;setupRelation:GateYardRelation;environmentAfter:{floor:'A'|'B'};leverContact:boolean;palletContact:boolean};
export function gateYardStopRecord(arm:GateYardArm,attempts:number):{kind:'stop';arm:GateYardArm;attempts:number;stoppedAt:string};
export function gateYardStudyExport(arm:GateYardArm,survey:{records?:readonly Record<string,unknown>[]}|null|undefined,stops?:readonly unknown[]):{version:1;study:'rail-golf-gate-yard-v1';arm:GateYardArm;exportedAt:string;attempts:Record<string,unknown>[];stops:unknown[]};
export function gateYardProgressSlice(stored:unknown,arm:GateYardArm):Record<string,unknown>;
export function gateYardProgressEnvelope(stored:unknown,arm:GateYardArm,records:unknown):{version:1;arms:Record<string,unknown>};
export function gateYardLibrarySlice(stored:unknown,arm:GateYardArm):{version:1;holes:unknown}|null;
export function gateYardLibraryEnvelope(stored:unknown,arm:GateYardArm,holes:unknown):{version:1;arms:Record<string,unknown>};
export function filterSurveyByArm(archive:ReturnType<typeof createSurveyArchive>,arm:GateYardArm):ReturnType<typeof createSurveyArchive>;
export function buildGateYardPallet(scene:Parameters<typeof buildDiverterLab>[0],root:Parameters<typeof buildDiverterLab>[1],materials:Parameters<typeof buildDiverterLab>[2],shadows:Parameters<typeof buildDiverterLab>[3],initial?:'A'|'B',target?:DiverterOptions['target'],geometry?:{floor?:DiverterOptions['floor'];switch?:DiverterOptions['switch']} | null):DiverterHandles;
