import type {LineEvidence} from './line-score';
import type {SavedLine} from './shot-library';
import type {SurveyRecord} from './survey-ledger';
export type IntentCondition='sentence'|'keep'|'score';
export type SentenceId='banks'|'treads'|'reverse';
export type IntentRelation=string|{action:string;attemptId?:string}|null;
export const INTENT_CONDITIONS:readonly IntentCondition[];
export const SENTENCES:readonly {id:SentenceId;station:'gate'|'lumber';label:string;clauses:readonly {surface:string;label:string}[]}[];
export type SentenceResult={id:string;reached:number;total:number;complete:boolean;labels:string[];headline:string};
export function matchIntentSentence(id:string,ledger:readonly LineEvidence[]):SentenceResult;
export type IntentEvent={kind:string;label:string;sourceIndex:number;feature?:string;surface?:string;state?:'A'|'B'};
export function recognizedIntentEvents(ledger:readonly LineEvidence[]):IntentEvent[];
export type KeptIntentLine={attemptId:string;line:SavedLine&{speed:number}};
export function keepIntentLine(kept:KeptIntentLine[],attemptId:string,line:SavedLine):KeptIntentLine[];
export function intentStorage(storage:Storage):Storage;
export function intentMeta(condition:IntentCondition,sentenceId?:string|null,relation?:IntentRelation):{intent:{condition:IntentCondition;sentenceId:string|null;relation:IntentRelation}};
export type IntentDecision={attemptId:string;action:'keep'|'discard';sequence:number;at:string};
export const INTENT_DECISION_LIMIT:number;
export function createIntentDecisions(storage:Pick<Storage,'getItem'|'setItem'|'removeItem'>):{append(attemptId:string,action:'keep'|'discard'):IntentDecision;export():IntentDecision[];warning():string;clear():void};
export type IntentStudyRecord=Omit<SurveyRecord,'receipt'>&{receipt?:SurveyRecord['receipt'];intent:ReturnType<typeof intentMeta>['intent'];orderedEvents:IntentEvent[];sentenceResult:SentenceResult|null;decision:IntentDecision|null;scoreTotal?:number};
export type IntentStudy={version:number;study:string;records:IntentStudyRecord[];decisions:IntentDecision[];note:string;exportedAt:string;warning?:string;limits?:unknown;evicted?:number};
export function exportIntentStudy(surveyExport:{records:SurveyRecord[];exportedAt:string;[key:string]:unknown},decisions:IntentDecision[]):IntentStudy;
export function intentStudyCSV(study:IntentStudy):string;
