import type {LineEvidence,RecordedLineReceipt} from './line-score';
import type {SavedLine} from './shot-library';
import type {SurveyRecord} from './survey-ledger';
import type {VectorLike} from './rail-golf-v02';
import type {captureLabLaunch} from './lab-controls';
import type {SentenceResult,IntentEvent} from './intent-lab';

export type LinecraftLessonId='banks'|'tread-pair'|'treads';
export type LinecraftOpenEntry='trained'|'cold'|'revisit';
export type LinecraftProgress=Record<LinecraftLessonId,{attempted:number;completed:boolean}>;
export type LinecraftExposure={entry:LinecraftOpenEntry;at:string;progress:LinecraftProgress};
export type LinecraftSession={stage:'learn'|'open';lessonIndex:number;progress:LinecraftProgress;scoreVisible:boolean;openEntry:LinecraftOpenEntry;attemptIds:string[];openExposures:LinecraftExposure[]};
export type LinecraftRelation=string|{action:string;attemptId?:string}|null;
export type LinecraftMeta={stage:'learn'|'open';lessonId:LinecraftLessonId|null;scoreVisible:boolean;openEntry:LinecraftOpenEntry;progress:LinecraftProgress;openExposures:LinecraftExposure[];relation:LinecraftRelation};
export type LinecraftTicketMeta={linecraft:LinecraftMeta;shelfAvailable?:number};
export const LINECRAFT_LESSONS:readonly {id:LinecraftLessonId;station:'gate'|'lumber';label:string;clauses:readonly {surface:string;label:string}[]}[];
export const LINECRAFT_SHELF_LIMIT:4;
export const LINECRAFT_REPLAY_SECONDS:6;
export function matchLinecraftSentence(id:string,ledger:readonly LineEvidence[]):SentenceResult;
export function createLinecraftSession():LinecraftSession;
export function linecraftMeta(session:LinecraftSession,relation?:LinecraftRelation):LinecraftTicketMeta;
export function recordLinecraftAttempt(session:LinecraftSession,attemptId:string,ledger:readonly LineEvidence[],fireMeta?:LinecraftTicketMeta|LinecraftMeta):LinecraftSession;
export function continueLinecraftSession(session:LinecraftSession):LinecraftSession;
export function enterLinecraftOpen(session:LinecraftSession,entry?:LinecraftOpenEntry):LinecraftSession;
export function linecraftStorage(storage:Storage):Storage;
export type LinecraftKeptEntry={attemptId:string;line:SavedLine&{speed:number};launchContext:ReturnType<typeof captureLabLaunch>;meta:LinecraftTicketMeta|LinecraftMeta;keptAt:string};
export function createLinecraftShelf(storage:Pick<Storage,'getItem'|'setItem'|'removeItem'>):{
 entries():LinecraftKeptEntry[];
 keep(attemptId:string,line:SavedLine,launchContext:ReturnType<typeof captureLabLaunch>,meta:LinecraftTicketMeta|LinecraftMeta):LinecraftKeptEntry|null;
 remove(attemptId:string):boolean;
 warning():string;
};
export type LinecraftDecision={attemptId:string;action:'keep';sequence:number;at:string;linecraft:LinecraftMeta;launchContext:ReturnType<typeof captureLabLaunch>;orderedEvents:IntentEvent[];sentenceResult:SentenceResult|null;ending:string;capacityAtFire?:number;scoreTotal?:number;lineReceipt?:RecordedLineReceipt};
export function createLinecraftDecisions(storage:Pick<Storage,'getItem'|'setItem'|'removeItem'>):{append(entry:LinecraftKeptEntry):LinecraftDecision;export():LinecraftDecision[];warning():string};
export type LinecraftStudyRecord=Omit<SurveyRecord,'receipt'>&{receipt?:SurveyRecord['receipt'];linecraft:LinecraftMeta;shelfAvailable?:number;orderedEvents:IntentEvent[];sentenceResult:SentenceResult|null;decision:LinecraftDecision|null;voluntarilyKept:boolean;scoreTotal?:number};
export type LinecraftStudy={version:number;study:string;records:LinecraftStudyRecord[];decisions:LinecraftDecision[];orphanKeepObservations:LinecraftDecision[];shelf:LinecraftKeptEntry[];note:string;exportedAt:string;warning?:string;limits?:unknown;evicted?:number};
export function exportLinecraftStudy(surveyExport:{records:SurveyRecord[];exportedAt:string;[key:string]:unknown},decisions:LinecraftDecision[],shelf?:LinecraftKeptEntry[]):LinecraftStudy;
export function linecraftStudyCSV(study:LinecraftStudy):string;
export function sampleRecordedPath(points:readonly VectorLike[],progress:number):VectorLike|null;
