import type {Scene,TransformNode,StandardMaterial,ShadowGenerator,Vector3,Mesh} from '@babylonjs/core';
import type {DiverterHandles,DiverterOptions} from './diverter-scene';
export const PALLET_YARD_PALLET:NonNullable<DiverterOptions['floor']>;
export const PALLET_YARD_LEVER:NonNullable<DiverterOptions['switch']>;
export const PALLET_YARD_FEATURE:{id:'pallet-yard-pallet';kind:'pallet';label:'PALLET'};
export const PALLET_EVIDENCE_CONTRACT:'pallet-evidence-v1';
export const PALLET_YARD_STORAGE_PREFIX:'rail-golf:pallet-yard:';
export const PALLET_YARD_RELATIONS:readonly ['fresh','adjust','retry','recall','current-yard'];
export const PALLET_YARD_SURVEY_DB:'rail-golf-pallet-yard-survey';
export type PalletYardKey='v8'|'n2';
export type PalletState='A'|'B';
export type PalletRelation=(typeof PALLET_YARD_RELATIONS)[number];
export type PalletFace='top'|'underside'|'end-x-'|'end-x+'|'near'|'far'|'edge';
export function parsePalletYardKey(value:string|null|undefined):PalletYardKey|null;
export function palletYardFlatB(key:PalletYardKey):boolean;
export function parsePalletYardStart(value:string|null|undefined):PalletState|null;
export function palletYardSlot(flatB:boolean):'0'|'1';
export function palletYardPrefix(flatB:boolean):string;
export function palletYardStorage(storage:Pick<Storage,'length'|'key'|'getItem'|'setItem'|'removeItem'>,flatB:boolean):Storage;
export function readPalletCarry(sessionStorage:Pick<Storage,'getItem'>,flatB:boolean):PalletState|null;
export function writePalletCarry(sessionStorage:Pick<Storage,'setItem'>,flatB:boolean,state:PalletState):void;
export function palletYardCurrentYardAvailable(current:PalletState,sourceState:PalletState|null|undefined):boolean;
export function classifyPalletFace(local:{x:number;y:number;z:number},floor?:NonNullable<DiverterOptions['floor']>):PalletFace;
export function legacyDeckContact(local:{y:number},floor?:NonNullable<DiverterOptions['floor']>):boolean;
export function palletYardEventList(ledger:readonly {kind?:string;feature?:string;label?:string;surface?:string;atStep?:number}[]):{text:string;atStep:number|null;sourceIndex:number}[];
export function palletYardEndingWord(reason:string|null|undefined):string;
export function palletYardSettledText(events:readonly {text:string}[],reason:string|null|undefined):string;
export function palletYardContactLabel(kind:string,events:readonly {text:string}[]):string|null;
export function groupPalletContacts(samples:readonly {step:number;face?:string;local:{x:number;y:number;z:number};world:{x:number;y:number;z:number};stateAtContact:PalletState}[],floor?:NonNullable<DiverterOptions['floor']>):{firstStep:number;lastStep:number;count:number;face:string;localPoint:{x:number;y:number;z:number};worldPoint:{x:number;y:number;z:number};stateAtContact:PalletState}[];
export function buildPalletEvidence(input:{stateAtLaunch:PalletState;stateAtEnd:PalletState;flips?:readonly {atStep:number;from:PalletState;to:PalletState}[];rawSamples?:readonly {step:number;face?:PalletFace;local:{x:number;y:number;z:number};world:{x:number;y:number;z:number};stateAtContact:PalletState}[];ledger?:readonly Record<string,unknown>[];displaySettled:string;displayLive?:readonly {text:string;atStep:number}[];addressChip:'PALLET A'|'PALLET B';setupRelation:PalletRelation;parentId?:string|null;sourceStateAtLaunch?:PalletState|null;setup:unknown;build:string;floor?:NonNullable<DiverterOptions['floor']>}):Record<string,unknown>;
export function palletEvidenceConsistent(record:Record<string,unknown>):string[];
export function palletYardStudyExport(attempts:readonly unknown[],extras?:{stateB?:'flat'|'rolled';stops?:readonly unknown[]}):{version:1;study:'rail-golf-pallet-yard';evidenceContract:'pallet-evidence-v1';exportedAt:string;stateB:'flat'|'rolled';attempts:unknown[];stops:unknown[]};
export function buildPalletYard(scene:Scene,root:TransformNode,materials:Record<string,StandardMaterial>,shadows:Pick<ShadowGenerator,'addShadowCaster'|'removeShadowCaster'>,initial?:PalletState,target?:null,options?:{flatB?:boolean;geometry?:{floor?:NonNullable<DiverterOptions['floor']>;switch?:NonNullable<DiverterOptions['switch']>}}):DiverterHandles&{notePallet(point:Vector3|null|undefined):{face:PalletFace;local:{x:number;y:number;z:number};world:{x:number;y:number;z:number};deck:boolean}|null;syncCue():void;cueMeshes():Mesh[]};
