export type VectorLike = { x: number; y: number; z: number };
export type ShotSetup = { railIndex: number; yaw: number; elevation: number; charge: number };
export type Outcome = "ace" | "breach" | "double" | "wet" | "oob" | "miss";
export type MechanismTag = "bank" | "boost" | "breach";
export type VolumeBox = { x: number; z: number; halfWidth: number; halfDepth: number; minY: number; maxY: number };
export type RangeTarget = { id: string; label: string; x: number; z: number; radius: number; material: "cyan" | "amber" | "violet" | "lime" };
export type Hole = {
  id: string;
  number: string;
  shortName: string;
  name: string;
  kicker: string;
  parLabel: string;
  instruction: string;
  courseLength: number;
  target: RangeTarget;
  requiredTags: readonly MechanismTag[];
  breach: VolumeBox | null;
  breachRecoveryY: number | null;
  water: VolumeBox | null;
  wind: { id: string; x: number; z: number; label: string; speedLabel: string };
  perfectAvailable: boolean;
  fairwayCenters: readonly number[];
  defaultShot: { railIndex: number; yaw: number; elevation: number };
  survey: { x: number; y: number; z: number; targetX: number; targetY: number; targetZ: number };
};
export type HoleRecord = {
  attempts: number;
  bestOutcome: Outcome | null;
  hasAce: boolean;
  hasBreach: boolean;
  perfect: boolean;
  cleared: boolean;
};
export const RAIL_RULES: Readonly<{
  gravity: number;
  minYaw: number;
  maxYaw: number;
  minElevation: number;
  maxElevation: number;
  minSpeed: number;
  maxSpeed: number;
  chargeSeconds: number;
  projectileMass: number;
  projectileRadius: number;
  landingHeight: number;
  muzzleLength: number;
  railPositions: readonly number[];
  theatreMilliseconds: number;
}>;
export const HOLES: readonly Hole[];
export const RANGE_TARGETS: readonly RangeTarget[];
export const RANGE_MECHANISMS: Readonly<Record<MechanismTag, VolumeBox>>;
export const REFERENCE_SHOTS: Readonly<Record<string, Readonly<ShotSetup>>>;
export function clamp(value: number, minimum: number, maximum: number): number;
export function stableUnitInterval(value: unknown): number;
export function clampYaw(value: number): number;
export function clampElevation(value: number): number;
export function chargeToSpeed(charge: number): number;
export function verticalRecoveryImpulse(currentYVelocity: number, targetYVelocity: number, mass?: number): number;
export function directionFromAim(yawDegrees: number, elevationDegrees: number): VectorLike;
export function addressCameraFrame(input: {
  railX: number;
  yawDegrees: number;
  target: Pick<RangeTarget, "x" | "z">;
  portrait?: boolean;
}): { position: VectorLike; target: VectorLike };
export function muzzleFromShot(shot: ShotSetup): VectorLike;
export function shiftRail(index: number, direction: number): number;
export function pointInsideAabb(point: VectorLike, box: VolumeBox): boolean;
export function segmentAabbIntersection(start: VectorLike, end: VectorLike, box: VolumeBox): number | null;
export function segmentSphereAabbIntersection(start: VectorLike, end: VectorLike, box: VolumeBox, radius?: number): number | null;
export function pointOnSegment(start: VectorLike, end: VectorLike, amount: number): VectorLike;
export function landingIntersection(start: VectorLike, end: VectorLike, landingHeight?: number): VectorLike | null;
export function isAceLanding(hole: Hole, point: VectorLike): boolean;
export function tagsMeetChallenge(hole: Hole, tags?: readonly string[]): boolean;
export function classifyChallengeRuling(input: { hole: Hole; targetHit: boolean; tags?: readonly string[]; wet?: boolean; outOfBounds?: boolean }): Outcome;
export function classifyRuling(input: { ace: boolean; breached: boolean; wet?: boolean; outOfBounds?: boolean }): Outcome;
export function rulingRank(outcome: Outcome): number;
export function isClear(outcome: Outcome): boolean;
export function normalizeHoleRecord(value: unknown): HoleRecord | null;
export function mergeHoleRecord(record: HoleRecord | undefined, outcome: Outcome): HoleRecord;
export function formatMiss(hole: Hole, point: VectorLike): string;
export function simulateShot(hole: Hole, shot: ShotSetup, stepSeconds?: number): { outcome: Outcome; breached: boolean; point: VectorLike; elapsed: number };
